import {requireCrmHost} from '@/lib/admin-host';
import {requireUser} from '@/lib/auth';
import {query} from '@/lib/db';
import {SiteHeader} from '@/components/site-header';
import {AnswerEditor} from '@/components/answer-editor';
import type {Answer} from '@/lib/coonto-help';
export const dynamic='force-dynamic';
export default async function HelpAdmin({searchParams}:{searchParams:Promise<{q?:string;status?:string;mode?:string}>}){
 await requireCrmHost();const user=await requireUser('/backoffice/ajuda');if(user.role!=='admin')return <main><h1>Acesso restrito</h1></main>;
 const params=await searchParams;const search=(params.q||'').slice(0,200);const status=['draft','approved','archived'].includes(params.status||'')?params.status!:'';const mode=['operational','teacher','student'].includes(params.mode||'')?params.mode!:'';
 const [answers,usage]=await Promise.all([query<Answer>(`SELECT * FROM coonto_answers WHERE ($1='' OR question ILIKE '%'||$1||'%' OR answer ILIKE '%'||$1||'%') AND ($2='' OR status=$2) AND ($3='' OR mode=$3) ORDER BY (status='draft') DESC,updated_at DESC LIMIT 100`,[search,status,mode]),query<{source:string;total:string;input:string;output:string;usd:string}>("SELECT source,COUNT(*)::text AS total,COALESCE(SUM(input_tokens),0)::text AS input,COALESCE(SUM(output_tokens),0)::text AS output,COALESCE(SUM(estimated_usd),0)::text AS usd FROM coonto_help_usage WHERE created_at>NOW()-INTERVAL '30 days' GROUP BY source ORDER BY source")]);
 return <main className="backoffice"><SiteHeader/><div className="content crm-page"><section className="backoffice-hero"><span className="section-kicker">CRM · AJUDA COONTO</span><h1>Perguntas e respostas</h1><p>Revise perguntas, corrija respostas e publique somente o que estiver aprovado. Respostas da IA entram como rascunhos. O contexto de obra, cena e progresso evita reutilizar uma resposta no momento errado.</p></section><section className="dashboard-card"><h2>Uso nos últimos 30 dias</h2><p>IA: {process.env.COONTO_AI_ENABLED==='true'&&process.env.OPENAI_API_KEY?'configurada':'aguarda ativação'}. ElevenLabs: {process.env.ELEVENLABS_API_KEY?'chave configurada; áudios ainda precisam ser produzidos':'aguarda chave e seleção das vozes'}. SMS: aguarda integração com fornecedor.</p><div className="help-usage-table"><table><thead><tr><th>Origem</th><th>Consultas</th><th>Tokens entrada</th><th>Tokens saída</th><th>Custo estimado (US$)</th></tr></thead><tbody>{usage.rows.map(row=><tr key={row.source}><td>{{bank:'Banco aprovado',ai:'IA',unanswered:'Sem resposta',pending:'Em processamento',error:'Falha da IA'}[row.source]||row.source}</td><td>{row.total}</td><td>{row.input}</td><td>{row.output}</td><td>{Number(row.usd).toFixed(5)}</td></tr>)}</tbody></table></div><p>A estimativa usa as tarifas configuradas no servidor; não substitui a fatura do fornecedor.</p></section><section className="dashboard-card"><h2>Localizar respostas</h2><form method="get" className="crm-inline-form"><label>Buscar<input name="q" defaultValue={search} placeholder="Pergunta ou resposta"/></label><label>Situação<select name="status" defaultValue={status}><option value="">Todas</option><option value="draft">Aguardando revisão</option><option value="approved">Aprovadas</option><option value="archived">Arquivadas</option></select></label><label>Área<select name="mode" defaultValue={mode}><option value="">Todas</option><option value="operational">Operacional</option><option value="teacher">Professor</option><option value="student">Estudante</option></select></label><button className="button button-primary">Pesquisar</button></form></section><section className="dashboard-card"><details><summary>Criar uma resposta</summary><AnswerEditor/></details></section><section className="dashboard-card"><h2>Banco de respostas · até 100 resultados</h2>{answers.rows.length?answers.rows.map(answer=><details key={answer.id} className="answer-row"><summary><strong>{answer.question}</strong><span>{answer.status==='approved'?'Aprovada':answer.status==='draft'?'Aguardando revisão':'Arquivada'} · {answer.mode==='operational'?'Operacional':answer.mode==='teacher'?'Professor':'Estudante'}</span></summary><AnswerEditor answer={answer}/></details>):<p>Nenhuma resposta encontrada.</p>}</section></div></main>;
}
