import { Play } from "lucide-react";
import { FormJump } from "@/components/form-jump";
import { FeedbackForm } from "@/components/feedback-form";
import { SiteFooter } from "@/components/site-footer";
import { SiteHeader } from "@/components/site-header";
import { getCommercialSettings } from "@/lib/commercial";
import { AccessOffers } from "@/components/access-offers";

export const dynamic = "force-dynamic";
export default async function Alienista() {
  const prices = await getCommercialSettings();
  return <main className="page"><SiteHeader /><FormJump target="feedback" label="Dar feedback ↓"/><section className="work-hero"><div className="content work-hero-grid"><div><span className="section-kicker">A PRIMEIRA EXPERIÊNCIA COONTO</span><h1>O Alienista</h1><p>Em Itaguaí, Simão Bacamarte quer estudar a mente humana. Ele é respeitado por seu conhecimento, mas uma ideia ambiciosa pode mudar a rotina de toda a cidade. E se você morasse lá? Entre na história e descubra o que acontece.</p><a href="/leitura/o-alienista" className="button button-coral"><Play size={18}/>Quero começar</a></div><div className="book-cover"><small>MACHADO DE ASSIS · COONTO</small><strong>Quem é louco<br/>nessa história?</strong><span>ENTRA → DECIDE → DESCOBRE → CONFERE</span></div></div></section><section className="offer-section" id="oferta"><div className="content"><span className="section-kicker">FORMAS DE ACESSO</span><h2>Comece pela obra gratuita. Conheça o que vem depois.</h2><p>Escolha O Alienista, Memórias de Martha ou o Canto I de Dante gratuitamente nesta beta. Ainda não há vendas nem assinatura ativa.</p><AccessOffers settings={prices}/></div></section><section className="experience-flow"><div className="content"><span className="section-kicker">COMO O COONTO FUNCIONA</span><h2>Uma pergunta leva você de volta ao livro.</h2><div className="flow-row"><div className="flow-step"><strong>1. Entre</strong><span>Conheça uma situação da história.</span></div><div className="flow-step"><strong>2. Escolha</strong><span>O que você acha que está acontecendo?</span></div><div className="flow-step"><strong>3. Descubra</strong><span>Observe as pistas e as consequências.</span></div><div className="flow-step"><strong>4. Confira</strong><span>Volte ao livro para sustentar ou rever sua interpretação.</span></div></div></div></section><section className="feedback-section" id="feedback"><div className="content feedback-layout"><div><span className="section-kicker">VOCÊ AJUDA A ESCREVER O PRÓXIMO PASSO</span><h2>Seu feedback não é um detalhe. É parte do produto.</h2><p>Queremos saber onde a experiência iluminou a obra, onde travou e o que precisa mudar. É assim que escolheremos as próximas obras e construiremos o Coonto Club.</p></div><FeedbackForm /></div></section><SiteFooter /></main>;
}
