const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),ts=require('typescript'),React=require('react'),{renderToStaticMarkup}=require('react-dom/server');
function load(file,mocks){const mod={exports:{}};vm.runInNewContext(ts.transpileModule(fs.readFileSync(file,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022,jsx:ts.JsxEmit.ReactJSX}}).outputText,{exports:mod.exports,module:mod,require:n=>mocks[n]||require(n),process,console});return mod.exports;}
const user={userId:'admin',role:'admin'},forms={setPersona:async()=>{},setCommercialScope:async()=>{},setCuratorWork:async()=>{}};
test('CRM mostra as três obras e conserva permissões distintas do curador',async()=>{
 const page=load('app/backoffice/personas/page.tsx',{'../crm/styles.css':{},'@/lib/admin-host':{requireCrmHost:async()=>{}},'@/lib/auth':{requireUser:async()=>user},'@/lib/access-control':{getAccessProfile:async()=>({globalOperation:true})},'@/components/site-header':{SiteHeader:()=>null},'./actions':forms,'@/lib/db':{query:async sql=>({rows:sql.includes('FROM users u')?[{id:'curator',name:'Curador fictício',contact:'curator@test.invalid',personas:['cultural_partner']}]:sql.includes('FROM curator_work_permissions')?[{user_id:'curator',work_slug:'divina-comedia-canto-i',can_comment:true,can_approve:false,can_publish:true}]:[]})}});
 const html=renderToStaticMarkup(await page.default());for(const title of ['O Alienista','Memórias de Martha','Dante · Inferno, Canto I'])assert.ok(html.includes(title));
 const renderedForms=html.match(/<form[\s\S]*?<\/form>/g).filter(s=>s.includes('name="work_slug"'));assert.equal(renderedForms.length,3);const dante=renderedForms.find(s=>s.includes('value="divina-comedia-canto-i"'));assert.equal((dante.match(/checked=""/g)||[]).length,2);for(const form of renderedForms.filter(s=>s!==dante))assert.equal(form.includes('checked=""'),false);
});
test('salvar permissão cultural altera só a obra selecionada e recusa conta sem administração',async()=>{
 let allowed=true;const calls=[];const actions=load('app/backoffice/personas/actions.ts',{'next/cache':{revalidatePath(){}},'@/lib/auth':{requireUser:async()=>user},'@/lib/access-control':{getAccessProfile:async()=>({globalOperation:allowed})},'@/lib/db':{query:async(sql,params)=>calls.push({sql,params})},'@/lib/transaction':{},'@/lib/administration-bootstrap':{}});
 const f=new FormData();f.set('user_id','curator');f.set('work_slug','divina-comedia-canto-i');f.set('can_comment','on');await actions.setCuratorWork(f);assert.deepEqual(Array.from(calls[0].params),['curator','divina-comedia-canto-i',true,false,false]);f.set('work_slug','unknown');await assert.rejects(()=>actions.setCuratorWork(f),/Dados inválidos/);allowed=false;f.set('work_slug','memorias-de-martha');await assert.rejects(()=>actions.setCuratorWork(f),/Apenas owners/);assert.equal(calls.length,1);
});
