const {test,before,after}=require('node:test');
const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),ts=require('typescript');
const {PGlite}=require('@electric-sql/pglite');
let db,contract;
function load(file,mocks={}){const mod={exports:{}};vm.runInNewContext(ts.transpileModule(fs.readFileSync(file,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022,jsx:ts.JsxEmit.ReactJSX}}).outputText,{exports:mod.exports,module:mod,require:n=>mocks[n]||require(n),process,console,Date,Intl,URL,Response,Request,crypto:require("node:crypto").webcrypto});return mod.exports;}
const query=(sql,params)=>db.query(sql,params);
const transaction=async work=>{await db.exec('BEGIN');try{const result=await work({query});await db.exec('COMMIT');return result;}catch(e){await db.exec('ROLLBACK');throw e;}};
const network=load('lib/education-network.ts',{'@/lib/db':{query}});
const access=load('lib/institutional-license-access.ts',{'@/lib/db':{query},'@/lib/education-network':network});
const licenses=load('lib/education-licenses.ts',{'@/lib/db':{query},'@/lib/transaction':{transaction},'@/lib/education-network':network,'@/lib/institutional-license-access':access,'@/lib/free-works':load('lib/free-works.ts')});
const reports=load('lib/education-reports.ts',{'@/lib/db':{query},'@/lib/education-network':network});
const sessions=load('lib/education-session.ts',{'next/navigation':{redirect:()=>{throw new Error('OTP')}},'@/lib/auth':{loginPath:p=>'/login?return_to='+encodeURIComponent(p)}});
before(async()=>{
 db=new PGlite();for(let round=0;round<2;round++)for(const file of fs.readdirSync('db/migrations').filter(f=>f.endsWith('.sql')).sort())await db.exec(fs.readFileSync('db/migrations/'+file,'utf8'));
 await db.exec(`INSERT INTO users(id,email,name,role) VALUES('admin','a@test.invalid','Admin','admin'),('buyer','b@test.invalid','Buyer','member'),('viewer','v@test.invalid','Viewer','member'),('limited','l@test.invalid','Limited','member'),('manager','m@test.invalid','Manager','member'),('teacher','t@test.invalid','Teacher','member'),('s1','s1@test.invalid','S1','member'),('s2','s2@test.invalid','S2','member'),('s3','s3@test.invalid','S3','member');
 INSERT INTO organizations(id,name,kind) VALUES('X','School X','school'),('Y','School Y','school'),('Z','School Z','school');
 INSERT INTO education_networks(id,name) VALUES('N','Network N'),('M','Network M');
 INSERT INTO education_network_memberships(network_id,user_id,can_manage_licenses,can_view_reports,can_drilldown) VALUES('N','buyer',true,false,false),('N','viewer',false,true,true),('N','limited',false,true,false);
 INSERT INTO education_network_schools(network_id,organization_id,can_allocate_licenses,can_share_reports) VALUES('N','X',true,true),('N','Y',true,false),('M','Z',true,true);
 INSERT INTO organization_memberships(organization_id,user_id,role) VALUES('X','manager','manager'),('X','teacher','teacher'),('Z','teacher','teacher'),('X','s1','student'),('X','s2','student'),('Y','s3','student');
 INSERT INTO classrooms(id,organization_id,name) VALUES('cx','X','X class'),('dx','X','X second class'),('cz','Z','Z class');
 INSERT INTO classroom_teachers(organization_id,classroom_id,user_id) VALUES('X','cx','teacher'),('X','dx','teacher'),('Z','cz','teacher');
 INSERT INTO classroom_enrollments(organization_id,classroom_id,user_id) VALUES('X','cx','s1'),('X','cx','s2'),('X','dx','s1');
 INSERT INTO educational_activities(id,organization_id,classroom_id,created_by,title,instructions) VALUES('ax','X','cx','teacher','Activity X','Instructions X'),('bx','X','dx','teacher','Activity second','Instructions X'),('az','Z','cz','teacher','Activity Z','Instructions Z');
 INSERT INTO educational_submissions(organization_id,activity_id,student_id,body) VALUES('X','ax','s1','Private institutional response'),('X','bx','s1','Second response');`);
});
after(async()=>await db.close());
test('comprador e gestor pedagógico têm capacidades independentes; outra rede não aparece',async()=>{
 const buyer=(await network.networkContexts('buyer'))[0];assert.equal(buyer.can_manage_licenses,true);assert.equal(buyer.can_view_reports,false);
 assert.equal((await network.networkSchools('buyer','M')).rows.length,0);
 assert.deepEqual((await network.networkSchools('viewer','N')).rows.map(s=>s.id),['X']);
 assert.equal(await licenses.schoolLicenseContext('viewer','X'),null);
 assert.equal((await licenses.schoolLicenseContext('buyer','X')).id,'X');
 const window=reports.reportWindow();assert.equal((await reports.networkReport('buyer','N',window)).activities,'0');
 assert.equal((await reports.networkReport('viewer','M',window)).activities,'0');
});
test('contratos confirmados só podem ser criados pela administração e reservas não excedem capacidade',async()=>{
 const from=new Date(Date.now()-86400000),until=new Date(Date.now()+10*86400000);
 assert.equal(await licenses.createNetworkContract('buyer','N','C1','o-alienista',2,from,until),false);
 assert.equal(await licenses.createNetworkContract('admin','N','C1','o-alienista',2,from,until),true);
 contract=(await licenses.networkContracts('buyer','N')).rows[0].id;
 assert.equal((await licenses.networkContracts('viewer','N')).rows.length,0);
 assert.equal(await licenses.allocateSchoolSeats('viewer','N',contract,'X',1),false);
 assert.equal(await licenses.allocateSchoolSeats('buyer','M',contract,'X',1),false);
 assert.equal(await licenses.allocateSchoolSeats('buyer','N',contract,'Z',1),false);
 assert.equal(await licenses.allocateSchoolSeats('buyer','N',contract,'X',1),true);
 assert.equal(await licenses.allocateSchoolSeats('buyer','N',contract,'Y',2),false);
 assert.equal(await licenses.allocateSchoolSeats('buyer','N',contract,'Y',1),true);
});
test('atribuição é idempotente e limitada às vagas e matrículas da escola',async()=>{
 assert.equal(await licenses.assignInstitutionalLicense('teacher','X',contract,'s1'),false);
 assert.equal(await licenses.assignInstitutionalLicense('buyer','X',contract,'s3'),false);
 assert.equal(await licenses.assignInstitutionalLicense('manager','X',contract,'s1'),true);
 assert.equal(await licenses.assignInstitutionalLicense('manager','X',contract,'s1'),true);
 assert.equal(await licenses.assignInstitutionalLicense('manager','X',contract,'s2'),false);
 assert.equal(await licenses.allocateSchoolSeats('buyer','N',contract,'X',0),false);
 assert.equal((await licenses.schoolLicenseStudents('viewer','X')).rows.length,0);
 assert.equal((await licenses.schoolLicenseStudents('buyer','X')).rows.length,2);
 assert.equal((await licenses.schoolLicenseGrants('viewer','X')).rows.length,0);
 assert.equal((await access.availableInstitutionalWorks('s1')).rows[0].work_slug,'o-alienista');
 assert.equal(await access.institutionalWorkAccess('s2','o-alienista'),null);
 const g=await access.institutionalWorkAccess('s1','o-alienista','used');assert.ok(g);assert.ok(g.expires_at);
 const k=(await licenses.networkContracts('buyer','N')).rows[0];assert.equal(k.activated,'1');assert.equal(k.used,'1');
 assert.equal(await licenses.revokeInstitutionalLicense('buyer','Y',g.id),false);
 assert.equal(await licenses.revokeInstitutionalLicense('viewer','X',g.id),false);
 assert.equal(await licenses.revokeInstitutionalLicense('manager','X',g.id),true);
 assert.equal(await access.institutionalWorkAccess('s1','o-alienista'),null);
 assert.equal(await licenses.assignInstitutionalLicense('manager','X',contract,'s2'),true);
});
test('relatórios contam pessoas únicas e participações, com detalhamento explicitamente autorizado',async()=>{
 const window=reports.reportWindow();const all=await reports.networkReport('viewer','N',window);
 assert.equal(all.activities,'2');assert.equal(all.eligible_participations,'3');assert.equal(all.eligible_people,'2');assert.equal(all.submitted,'2');assert.equal(all.submitted_people,'1');
 assert.equal((await reports.networkReport('viewer','N',window,'Z')).activities,'0');
 assert.equal((await reports.networkReport('limited','N',window,'X')).activities,'0');
 assert.equal((await reports.networkReport('limited','N',window,undefined,'teacher')).activities,'0');
 assert.deepEqual((await reports.networkSchoolTeachers('viewer','N','X')).rows.map(t=>t.id),['teacher']);
 assert.equal((await reports.networkSchoolClasses('viewer','N','X','teacher')).rows.length,2);
 assert.equal((await reports.networkSchoolClasses('viewer','N','Z','teacher')).rows.length,0);
 assert.equal((await reports.networkReport('viewer','N',window,'X','teacher','cx')).eligible_participations,'2');
 assert.equal(JSON.stringify(all).includes('Private institutional response'),false);
});
test('download inválido não ativa licença e emissão offline respeita o fim do contrato',async()=>{
 const member=load('lib/member.ts',{'@/lib/auth':{getCurrentUser:async()=>({userId:'s2',role:'member'})},'@/lib/db':{query},'@/lib/institutional-license-access':access});
 const route=load('app/api/offline-license/route.ts',{'@/lib/member':member,'@/lib/free-works':load('lib/free-works.ts'),'@/lib/request-origin':load('lib/request-origin.ts'),'@/lib/transaction':{transaction}});
 const request=deviceId=>new Request('https://coonto.test/api/offline-license',{method:'POST',headers:{origin:'https://coonto.test','Content-Type':'application/json'},body:JSON.stringify({workSlug:'o-alienista',deviceId})});
 assert.equal((await route.POST(request('bad'))).status,400);
 assert.equal((await query("SELECT activated_at FROM education_license_grants WHERE contract_id=$1 AND user_id='s2'",[contract])).rows[0].activated_at,null);
 const result=await route.POST(request('browser-test-device'));assert.equal(result.status,200);const body=await result.json();
 const end=(await query('SELECT valid_until FROM education_license_contracts WHERE id=$1',[contract])).rows[0].valid_until;
 assert.ok(new Date(body.expiresAt)<=new Date(end));
 assert.ok((await query("SELECT activated_at FROM education_license_grants WHERE contract_id=$1 AND user_id='s2'",[contract])).rows[0].activated_at);
});
test('revogação, vigência e contrato interrompem novos acessos, sem alterar licença pessoal',async()=>{
 await query("UPDATE organization_memberships SET status='revoked' WHERE organization_id='X' AND user_id='s2'");assert.equal(await access.institutionalWorkAccess('s2','o-alienista'),null);
 await query("UPDATE organization_memberships SET status='active' WHERE organization_id='X' AND user_id='s2'");
 await query("UPDATE education_network_schools SET can_allocate_licenses=false WHERE network_id='N' AND organization_id='X'");assert.equal(await access.institutionalWorkAccess('s2','o-alienista'),null);
 await query("UPDATE education_network_schools SET can_allocate_licenses=true WHERE network_id='N' AND organization_id='X'");
 await query("UPDATE education_license_contracts SET valid_until=NOW()-INTERVAL '1 hour',valid_from=NOW()-INTERVAL '2 days' WHERE id=$1",[contract]);
 assert.equal(await access.institutionalWorkAccess('s2','o-alienista'),null);assert.equal(await licenses.assignInstitutionalLicense('buyer','X',contract,'s1'),false);
 await query("INSERT INTO entitlements(id,user_id,work_slug) VALUES('personal','s2','o-alienista')");
 const member=load('lib/member.ts',{'@/lib/auth':{getCurrentUser:async()=>null},'@/lib/db':{query},'@/lib/institutional-license-access':access});assert.equal((await member.ensureWorkEntitlement('s2','o-alienista')).id,'personal');
 await query("UPDATE education_network_memberships SET status='revoked' WHERE network_id='N' AND user_id='viewer'");assert.equal((await network.networkContexts('viewer')).length,0);
 assert.equal((await reports.networkReport('viewer','N',reports.reportWindow())).activities,'0');
});
test('datas inválidas são rejeitadas; confirmação diária usa o dia de São Paulo',()=>{
 for(const dates of [['2026-99-01','2026-10-03'],['2026-02-30','2026-10-03'],['2026-10-05','2026-10-03'],['2024-01-01','2026-10-03']])assert.equal(reports.reportWindow(...dates),null);
 const w=reports.reportWindow('2026-10-03','2026-10-03');assert.equal(w.start.toISOString(),'2026-10-03T03:00:00.000Z');assert.equal(w.end.toISOString(),'2026-10-04T03:00:00.000Z');
 const now=new Date('2026-10-04T02:50:00Z');assert.equal(sessions.verifiedToday('2026-10-03T03:00:00Z',now),true);assert.equal(sessions.verifiedToday('2026-10-03T02:59:00Z',now),false);assert.equal(sessions.verifiedToday('2026-10-04T03:00:00Z',now),false);
 assert.throws(()=>sessions.requireEducationVerification({authenticatedAt:undefined},'/gestao-rede'),/OTP/);
});
test('contexto lembrado é apenas navegação e precisa continuar autorizado para a mesma conta',()=>{
 const navigation=load('lib/navigation-context.ts');
 const profile={personas:['reader'],globalOperation:false,canUseCommercialCrm:false,canUseCulturalCrm:false};
 const choices=navigation.contextDestinations(profile,[{id:'X',name:'X',role:'teacher'}],[]);
 assert.equal(navigation.rememberedDestination(JSON.stringify({userId:'teacher',key:'school:X'}),'teacher',choices),'/gestao-escolar?instituicao=X');
 assert.equal(navigation.rememberedDestination(JSON.stringify({userId:'teacher',key:'school:Y'}),'teacher',choices),null);
 assert.equal(navigation.rememberedDestination(JSON.stringify({userId:'other',key:'school:X'}),'teacher',choices),null);
 assert.equal(navigation.rememberedDestination(JSON.stringify({userId:'teacher',key:'network:N'}),'teacher',choices),null);
 assert.equal(navigation.rememberedDestination('{broken','teacher',choices),null);
 assert.equal(navigation.rememberedDestination(JSON.stringify({userId:'teacher',key:'school:X'}),'teacher',navigation.contextDestinations(profile,[],[])),null);
});
