import {requireUser} from '@/lib/auth';
import {requireCrmHost} from '@/lib/admin-host';
import {query} from '@/lib/db';
import {SiteHeader} from '@/components/site-header';
import {freeWorks} from '@/lib/free-works';
import {createNetwork,changeNetworkMember,changeNetworkSchool,registerContract,revokeContract} from './actions';
export const dynamic='force-dynamic';
export default async function Networks({searchParams}:{searchParams:Promise<{salvo?:string}>}){
 await requireCrmHost();const user=await requireUser('/backoffice/redes');if(user.role!=='admin')return <main className="page"><SiteHeader/><h1>Área restrita</h1></main>;
 const networks=await query<{id:string;name:string}>('SELECT id,name FROM education_networks ORDER BY name,id');
 const schools=await query<{id:string;name:string}>("SELECT id,name FROM organizations WHERE kind IN ('school','course') AND status='active' ORDER BY name,id");
 const members=await query<{network_id:string;email:string;name:string;can_manage_licenses:boolean;can_view_reports:boolean;can_drilldown:boolean;status:string}>(`SELECT m.*,u.email,u.name FROM education_network_memberships m JOIN users u ON u.id=m.user_id ORDER BY u.name`);
 const links=await query<{network_id:string;organization_id:string;name:string;status:string;can_allocate_licenses:boolean;can_share_reports:boolean}>(`SELECT ns.*,o.name FROM education_network_schools ns JOIN organizations o ON o.id=ns.organization_id ORDER BY o.name`);
 const contracts=await query<{id:string;network_id:string;reference:string;work_slug:string;seats:number;status:string}>(`SELECT id,network_id,reference,work_slug,seats,status FROM education_license_contracts ORDER BY created_at DESC`);
 const params=await searchParams;
 return <main className="page"><SiteHeader/><div className="content member-page"><section className="page-hero"><span className="section-kicker">COONTO ADMINISTRAÇÃO</span><h1>Redes, permissões e contratos</h1><p>Uma rede pode comprar licenças sem receber dados pedagógicos. O compartilhamento precisa ser autorizado em cada vínculo rede–escola e no acesso da pessoa.</p>{params.salvo&&<p role="status">Alteração salva.</p>}</section>
 <section className="dashboard-card"><h2>Criar rede ou mantenedora</h2><form action={createNetwork} className="crm-inline-form"><label className="field">Nome<input name="name" required minLength={2} maxLength={200}/></label><button className="button button-primary">Criar rede</button></form></section>
 {networks.rows.map(n=><section className="dashboard-card" key={n.id}><h2>{n.name}</h2><h3>Pessoas autorizadas</h3>{members.rows.filter(m=>m.network_id===n.id).map(m=><p key={m.email}>{m.name} · {m.email} · {m.status==='active'?'Ativo':'Revogado'} · {m.can_manage_licenses?'Licenças':'Sem licenças'} · {m.can_view_reports?'Relatórios':'Sem relatórios'} · {m.can_drilldown?'Detalhamento':'Sem detalhamento'}</p>)}
 <form action={changeNetworkMember}><input type="hidden" name="network" value={n.id}/><label className="field">E-mail da conta existente<input type="email" name="email" required maxLength={320}/></label><fieldset className="crm-checks"><legend>Permissões da pessoa</legend><label><input type="checkbox" name="licenses"/> Administrar licenças</label><label><input type="checkbox" name="reports"/> Consultar relatórios</label><label><input type="checkbox" name="drilldown"/> Detalhar escola, professor e turma</label></fieldset><label className="field">Acesso<select name="status"><option value="active">Ativo</option><option value="revoked">Revogado</option></select></label><p>Ao salvar uma conta existente, estas permissões substituem as anteriores.</p><button className="button button-primary">Definir acesso</button></form>
 <h3>Escolas vinculadas</h3>{links.rows.filter(s=>s.network_id===n.id).map(s=><p key={s.organization_id}>{s.name} · {s.status==='active'?'Vínculo ativo':'Vínculo revogado'} · {s.can_allocate_licenses?'Licenças autorizadas':'Sem licenças'} · {s.can_share_reports?'Relatórios autorizados':'Sem relatórios'}</p>)}
 <form action={changeNetworkSchool}><input type="hidden" name="network" value={n.id}/><label className="field">Escola<select name="school" required><option value="">Selecione</option>{schools.rows.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label><fieldset className="crm-checks"><legend>Autorizações da escola</legend><label><input type="checkbox" name="licenses"/> Autorizar distribuição de licenças</label><label><input type="checkbox" name="reports"/> Autorizar compartilhamento de relatórios</label></fieldset><label className="field">Vínculo<select name="status"><option value="active">Ativo</option><option value="revoked">Revogado</option></select></label><button className="button button-primary">Definir vínculo</button></form>
 <h3>Registrar contrato confirmado</h3><form action={registerContract} className="crm-inline-form"><input type="hidden" name="network" value={n.id}/><label className="field">Referência<input name="reference" required minLength={2} maxLength={160}/></label><label className="field">Obra<select name="work">{freeWorks.map(w=><option key={w.slug} value={w.slug}>{w.title}</option>)}</select></label><label className="field">Licenças contratadas<input type="number" name="seats" required min={1} max={1000000}/></label><label className="field">Início<input name="from" type="date" required/></label><label className="field">Último dia de validade<input name="until" type="date" required/></label><button className="button button-primary">Registrar contrato</button></form>
 {contracts.rows.filter(k=>k.network_id===n.id).map(k=><div className="status-item" key={k.id}><p>{k.reference} · {k.work_slug} · {k.seats} licença(s) · {k.status==='active'?'Ativo':'Revogado'}</p>{k.status==='active'&&<form action={revokeContract}><input type="hidden" name="contract" value={k.id}/><button className="button">Revogar contrato</button></form>}</div>)}
 </section>)}
 </div></main>;
}
