"use client";
import {useActionState,useState} from 'react';
import {useRouter} from 'next/navigation';
import {generateAudio,approveAudio,type AudioResult} from '@/app/backoffice/audio/actions';
import type {AudioJob,AudioInput} from '@/lib/audio-production';
type Scene={id:string;title:string;segments:AudioInput['segments']};
const empty:AudioResult={ok:false,message:''};
function Review({job,onEdit}:{job:AudioJob;onEdit:(job:AudioJob)=>void}){
 const[result,action,pending]=useActionState(approveAudio,empty);
 return <article className="audio-review"><p><strong>{job.status==='published'?'Publicado':job.status==='ready'?'Aguardando aprovação':job.status==='failed'?'Falha na geração':'Geração iniciada'}</strong> · {new Date(job.created_at).toLocaleString('pt-BR')} · {job.characters} caracteres</p><details><summary>Ver o texto desta versão</summary>{job.segments.map((s,i)=><p key={i}><strong>{s.speaker==='narrator'?'Narradora':'Bacamarte'}:</strong> {s.text}</p>)}</details>{['ready','published'].includes(job.status)&&<><button type="button" className="link-button" onClick={()=>onEdit(job)}>Usar este texto para corrigir</button><audio controls preload="none" src={'/api/backoffice/audio/'+job.id} aria-label="Ouvir esta versão"/><form action={action}><input type="hidden" name="jobId" value={job.id}/><button className="button button-primary" disabled={pending||job.status==='published'}>{pending?'Publicando…':job.status==='published'?'Áudio publicado':'Aprovar e publicar esta versão'}</button></form></>}{job.error_message&&<p>{job.error_message}</p>}{job.status==='generating'&&<p>Se a operação foi interrompida, confira o saldo no ElevenLabs antes de gerar novamente.</p>}{result.message&&<p role="status">{result.message}</p>}</article>;
}
function Editor({scene,ready,busy}:{scene:Scene;ready:boolean;busy:boolean}){
 const[segments,setSegments]=useState<AudioInput['segments']>(scene.segments);
 const[result,action,pending]=useActionState(generateAudio,empty);
 const chars=segments.reduce((n,s)=>n+s.text.trim().length,0);
 const valid=chars>0&&chars<=5000&&segments.every(s=>s.text.trim());
 return <form action={action} className="answer-editor"><input type="hidden" name="sceneId" value={scene.id}/><input type="hidden" name="segments" value={JSON.stringify(segments)}/>{segments.map((segment,index)=><div key={index}><label>Voz do trecho {index+1}<select value={segment.speaker} onChange={event=>setSegments(segments.map((s,i)=>i===index?{...s,speaker:event.target.value as 'narrator'|'bacamarte'}:s))}><option value="narrator">Narradora · feminina</option><option value="bacamarte">Bacamarte · masculina</option></select></label><label>Texto a ser falado<textarea rows={5} maxLength={5000} value={segment.text} onChange={event=>setSegments(segments.map((s,i)=>i===index?{...s,text:event.target.value}:s))}/></label>{segments.length>1&&<button type="button" className="link-button" onClick={()=>setSegments(segments.filter((_,i)=>i!==index))}>Remover trecho</button>}</div>)}{segments.length<2&&<button type="button" className="link-button" onClick={()=>setSegments([...segments,{speaker:'bacamarte',text:''}])}>Adicionar fala de Bacamarte</button>}<p>Prévia: <strong>{chars.toLocaleString('pt-BR')} caracteres</strong>. Gerar ou corrigir consome créditos do ElevenLabs. Ouvir e aprovar não gera nova cobrança. O saldo exato depende do plano e do modelo.</p><p>Use a voz de Bacamarte apenas em falas revisadas do personagem. Identifique adaptações no texto da experiência; não atribua a ele a explicação da narradora.</p><button className="button button-primary" disabled={!ready||busy||pending||!valid}>{pending?'Gerando rascunho…':'Gerar rascunho · usa créditos'}</button>{result.message&&<p role="status">{result.message}</p>}{result.ok&&result.jobId&&<audio controls preload="none" src={'/api/backoffice/audio/'+result.jobId} aria-label="Ouvir novo rascunho"/>}</form>;
}
export function AudioStudio({scenes,jobs,ready}:{scenes:Scene[];jobs:AudioJob[];ready:boolean}){
 const[selected,setSelected]=useState('s2');const[editing,setEditing]=useState<AudioJob|null>(null);const[search,setSearch]=useState('');const[batch,setBatch]=useState(false);const[message,setMessage]=useState('');const router=useRouter();
 const scene=scenes.find(s=>s.id===selected)!;
 const remaining=scenes.filter(s=>!jobs.some(j=>j.scene_id===s.id&&['ready','published'].includes(j.status)));
 const total=remaining.reduce((n,s)=>n+s.segments.reduce((m,x)=>m+x.text.length,0),0);
 async function generateRemaining(){
  setBatch(true);let done=0;
  try{for(const scene of remaining){setMessage(`Gerando ${done+1} de ${remaining.length}: ${scene.title}. Mantenha esta página aberta.`);const form=new FormData();form.set('sceneId',scene.id);form.set('segments',JSON.stringify(scene.segments));const result=await generateAudio(empty,form);if(!result.ok){setMessage(`Lote interrompido: ${result.message} ${done} cenas concluídas; elas ficaram salvas para revisão.`);return;}done++;}setMessage(`${done} rascunhos gerados. Revise e aprove cada cena na lista.`);}catch{setMessage('A conexão foi interrompida. Atualize a página para conferir as versões salvas antes de retomar.');}finally{setBatch(false);router.refresh();}
 }
 return <><section className="dashboard-card"><h2>Gerar as demais cenas para revisão</h2><p>Depois de aprovar a primeira amostra, você pode gerar as narrações restantes em sequência. Cada uma fica como rascunho, sem publicação automática. Cenas que já têm um rascunho concluído ou publicado são preservadas.</p><p><strong>{remaining.length} cenas · {total.toLocaleString('pt-BR')} caracteres previstos.</strong> Este lote usa somente os roteiros de narração; falas de Bacamarte são preparadas individualmente abaixo.</p><button className="button button-primary" disabled={!ready||batch||!remaining.length||!jobs.some(j=>j.status==='published')} onClick={generateRemaining}>{batch?'Gerando…':'Gerar restantes · usa créditos'}</button>{!jobs.some(j=>j.status==='published')&&<p>Aprove uma amostra antes de liberar o lote.</p>}{message&&<p role="status">{message}</p>}</section><section className="dashboard-card"><h2>Escolher uma cena</h2><label className="field">Localizar<input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Título ou número da cena"/></label><div className="audio-scene-list">{scenes.filter(s=>`${s.title} ${s.id}`.toLocaleLowerCase('pt-BR').includes(search.toLocaleLowerCase('pt-BR'))).map(s=>{const versions=jobs.filter(j=>j.scene_id===s.id);return <button type="button" className="audio-scene-button" aria-pressed={selected===s.id} disabled={batch} key={s.id} onClick={()=>{setSelected(s.id);setEditing(null);}}>{Number(s.id.slice(1))+1}. {s.title}<small>{versions.some(j=>j.status==='published')?'Publicado':versions.some(j=>j.status==='ready')?'Aguardando aprovação':'Sem áudio aprovado'}</small></button>;})}</div></section><section className="dashboard-card"><h2>{scene.title}</h2><Editor key={scene.id+(editing?.id||'')} scene={editing?{...scene,segments:editing.segments}:scene} ready={ready} busy={batch}/></section><section className="dashboard-card"><h2>Ouvir e aprovar · {scene.title}</h2><p>O áudio atual permanece na leitura enquanto você corrige um novo rascunho. Versões anteriores podem ser republicadas sem consumir novos créditos.</p>{jobs.filter(j=>j.scene_id===scene.id).map(job=><Review key={job.id} job={job} onEdit={setEditing}/>)}{!jobs.some(j=>j.scene_id===scene.id)&&<p>Nenhuma versão gerada para esta cena.</p>}</section></>;
}
