"use client";
import {useEffect,useRef,useState} from 'react';
import type {HelpMode} from '@/lib/coonto-help';
const labels={operational:'Como usar o Coonto',teacher:'Apoio ao professor',student:'Apoio à minha leitura'};
type Message={role:'user'|'assistant';text:string;source?:string};
export function CoontoHelp({initialMode='operational',sceneId}:{initialMode?:HelpMode;sceneId?:string}){
 const generation=useRef(0);
 const[mode,setMode]=useState<HelpMode>(initialMode),[questions,setQuestions]=useState<{id:string;question:string}[]>([]),[question,setQuestion]=useState(''),[messages,setMessages]=useState<Message[]>([]),[busy,setBusy]=useState(false),[error,setError]=useState('');
 useEffect(()=>{let alive=true;generation.current++;setBusy(false);setQuestions([]);setMessages([]);setError('');void fetch(`/api/ajuda?mode=${mode}${sceneId?`&sceneId=${encodeURIComponent(sceneId)}`:''}`).then(async r=>{const data=await r.json();if(!r.ok)throw new Error(data.error);if(alive)setQuestions(data.questions);}).catch(e=>{if(alive)setError(e.message||'Não foi possível abrir a ajuda.');});return()=>{alive=false;};},[mode,sceneId]);
 async function ask(text:string){if(busy||!text.trim())return;const activeGeneration=generation.current;setBusy(true);setError('');setQuestion('');setMessages(items=>[...items,{role:'user',text}]);try{const response=await fetch('/api/ajuda',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({mode,question:text,sceneId,history:messages.slice(-6).map(m=>({role:m.role,text:m.text}))})});const data=await response.json();if(!response.ok)throw new Error(data.error||'Não foi possível responder.');if(activeGeneration===generation.current)setMessages(items=>[...items,{role:'assistant',text:data.answer,source:data.source}]);}catch(e){if(activeGeneration===generation.current)setError(e instanceof Error?e.message:'Não foi possível responder.');}finally{if(activeGeneration===generation.current)setBusy(false);}}
 return <section className="coonto-help" aria-label="Ajuda Coonto"><div className="help-heading"><div><span className="section-kicker">AJUDA COONTO</span><h2>Uma pergunta, um próximo passo.</h2></div><label>Como podemos ajudar?<select value={mode} disabled={busy} onChange={e=>setMode(e.target.value as HelpMode)}>{Object.entries(labels).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label></div><p>{mode==='student'?'Vamos trabalhar com pistas da sua etapa atual, sem antecipar a história.':mode==='teacher'?'Prepare perguntas e atividades para antes, durante e depois da leitura.':'Encontre orientações para usar a plataforma.'}</p><div className="help-questions">{questions.map(q=><button key={q.id} disabled={busy} onClick={()=>void ask(q.question)}>{q.question}</button>)}</div><div className="help-messages" aria-live="polite">{messages.map((message,i)=><div key={i} className={`help-message ${message.role}`}><strong>{message.role==='user'?'Você':'Coonto'}</strong><p>{message.text}</p>{message.source&&<small>{message.source}</small>}</div>)}</div>{error&&<p role="alert" className="help-error">{error} <a href="/login?return_to=%2Fajuda">Entrar</a> · <a href="/professor">Espaço do professor</a></p>}<form onSubmit={e=>{e.preventDefault();void ask(question);}}><label htmlFor={`question-${initialMode}`}>Sua pergunta</label><textarea id={`question-${initialMode}`} value={question} maxLength={1200} onChange={e=>setQuestion(e.target.value)} rows={3} required placeholder="Escreva sua dúvida…"/><button className="button button-primary" disabled={busy||!question.trim()}>{busy?'Buscando uma orientação…':'Enviar pergunta'}</button></form><small>As perguntas enviadas ficam disponíveis para revisão pela equipe Coonto. Respostas geradas pela IA são identificadas e precisam de revisão antes de entrar no banco aprovado.</small></section>;
}
