"use client";
import {useEffect,useState} from 'react';
import type {RcWork} from '@/lib/rc-schema';
type Permission={work_slug:string;can_comment:boolean;can_approve:boolean;can_publish:boolean};
type Version={id:string;work_slug:string;status:string;content:RcWork;created_at:string};
export function RcEditor(){
 const[data,setData]=useState<{permissions:Permission[];defaults:RcWork[];versions:Version[]}|null>(null),[slug,setSlug]=useState(''),[draft,setDraft]=useState(''),[status,setStatus]=useState('Carregando…'),[busy,setBusy]=useState(false);
 async function load(){const response=await fetch('/api/rc/editor',{cache:'no-store'});const body=await response.json();if(!response.ok)throw new Error(body.error);setData(body);return body;}
 useEffect(()=>{load().then(body=>{const first=body.defaults[0];if(first){setSlug(first.slug);setDraft(JSON.stringify(first,null,2));}setStatus('');}).catch(error=>setStatus(error.message));},[]);
 async function act(input:unknown){setBusy(true);try{const response=await fetch('/api/rc/editor',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(input)});const body=await response.json();if(!response.ok)throw new Error(body.error);await load();setStatus('Operação concluída.');}catch(error){setStatus(error instanceof Error?error.message:'Erro na operação.');}finally{setBusy(false);}}
 const permission=data?.permissions.find(p=>p.work_slug===slug);
 return <section className="dashboard-card"><h2>Conteúdo versionado</h2><p>Edite a síntese, perguntas e retornos. Cada salvamento cria uma nova versão. Aprovar e publicar são operações separadas. A fonte, a licença e a ordem dos capítulos permanecem protegidas.</p><p role="status">{status}</p>{data&&<><label className="field">Obra<select value={slug} onChange={e=>{setSlug(e.target.value);setDraft(JSON.stringify(data.defaults.find(w=>w.slug===e.target.value),null,2));}}>{data.defaults.map(w=><option key={w.slug} value={w.slug}>{w.title}</option>)}</select></label>{permission?.can_comment&&<><label className="field">Rascunho editorial em JSON<textarea rows={18} value={draft} onChange={e=>setDraft(e.target.value)} spellCheck={false}/></label><button type="button" className="button button-primary" disabled={busy} onClick={()=>{try{void act({action:'draft',slug,content:JSON.parse(draft)});}catch{setStatus('JSON inválido: confira a sintaxe antes de salvar.');}}}>Salvar nova versão como rascunho</button></>}<h3>Histórico · {slug}</h3>{data.versions.filter(v=>v.work_slug===slug).map(v=><article className="rc-editor-version" key={v.id}><p><strong>{v.status}</strong> · {new Date(v.created_at).toLocaleString('pt-BR')} · {v.id}</p><div className="after-actions"><button type="button" className="button button-outline" onClick={()=>{setDraft(JSON.stringify(v.content,null,2));setStatus('Versão carregada no editor. Salvar criará um novo rascunho.');}}>Carregar no editor</button>{v.status==='draft'&&permission?.can_approve&&<button type="button" className="button button-outline" disabled={busy} onClick={()=>void act({action:'approve',id:v.id})}>Aprovar conteúdo</button>}{v.status==='approved'&&permission?.can_publish&&<button type="button" className="button button-primary" disabled={busy} onClick={()=>void act({action:'publish',id:v.id})}>Publicar versão aprovada</button>}</div></article>)}<p>Sem versão publicada no CRM, a experiência usa a edição beta entregue no aplicativo. Alterar a abertura torna o áudio anterior indisponível até uma nova produção; não se apresenta áudio desatualizado como atual.</p></>}</section>;
}
