"use client";
import {BookOpen,CircleHelp,Download,Library,Pause,Play,Save} from 'lucide-react';
import {useEffect,useRef,useState} from 'react';
import {prepareRcState,rcInteractions,initialRcState,rcStages,rcProgress,rcStateSchema,validRcState,type RcState,type RcWork} from '@/lib/rc-schema';
import verses from '@/content/inferno-i-verses.json';

export function RcLiteraryExperience({work,signedIn}:{work:RcWork;signedIn:boolean}){
 const[state,setState]=useState<RcState>(()=>prepareRcState(initialRcState,work)),[loaded,setLoaded]=useState(!signedIn),[status,setStatus]=useState(signedIn?'Carregando seu histórico…':'Sem conta: anotações apenas nesta página.'),[help,setHelp]=useState(false),[audioError,setAudioError]=useState(false),[speaking,setSpeaking]=useState(false),[preparing,setPreparing]=useState(false);
 const audio=useRef<HTMLAudioElement|null>(null),canvas=useRef<HTMLDivElement|null>(null);
 const owner=useRef<string|null>(null);
 const revision=useRef(0),dirty=useRef(false),saving=useRef(false),blocked=useRef(false),stateRef=useRef(state),generation=useRef(0);
 stateRef.current=state;
 useEffect(()=>{if(!signedIn)return;let active=true;fetch(`/api/rc/progress/${work.slug}`,{cache:'no-store'}).then(async response=>{const body=await response.json();if(!response.ok)throw new Error(body.error||'Não foi possível carregar seu histórico.');if(!active)return;if(body.progress){const parsed=rcStateSchema.safeParse(body.progress.state);if(!parsed.success||!validRcState(parsed.data,work))throw new Error('Histórico incompatível.');setState(prepareRcState(parsed.data,work));revision.current=body.progress.revision;}setStatus(body.progress?.contentVersion&&body.progress.contentVersion!==work.version?'Seu histórico foi retomado na edição atual. As notas anteriores foram preservadas; as novas perguntas têm respostas próprias.':'Histórico carregado.');owner.current=body.userId;let pending=null;try{pending=JSON.parse(localStorage.getItem('coonto-rc-pending-'+body.userId+'-'+work.slug)||'null');}catch{}if(pending){const parsed=rcStateSchema.safeParse(pending.state);if(parsed.success&&validRcState(parsed.data,work)){setState(prepareRcState(parsed.data,work));if(pending.revision===(body.progress?.revision||0)&&pending.contentVersion===work.version){dirty.current=true;generation.current++;setStatus('Sincronizando suas anotações do aparelho…');}else{blocked.current=true;setStatus('Há notas offline e uma edição ou histórico mais recente na conta. Baixe suas notas antes de recarregar; nenhum histórico será sobrescrito.');}}}setLoaded(true);}).catch(error=>{if(active){setStatus(error.message);blocked.current=true;setLoaded(true);}});return()=>{active=false;};},[signedIn,work.slug,work.version,work.units.length]);
 function change(next:RcState){dirty.current=true;generation.current++;setState(next);setStatus(signedIn?'Alterações ainda não salvas.':'Sem conta: anotações apenas nesta página.');}
 async function save(){if(!signedIn||!loaded||blocked.current||saving.current||!dirty.current)return;saving.current=true;const sent=generation.current;setStatus('Salvando…');try{const response=await fetch(`/api/rc/progress/${work.slug}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({state:stateRef.current,revision:revision.current,contentVersion:work.version})});const body=await response.json();if(!response.ok){if(response.status===409||response.status===401)blocked.current=true;throw new Error(body.error||'Não foi possível salvar. Tente novamente.');}revision.current=body.revision;dirty.current=generation.current!==sent;if(!dirty.current&&owner.current){localStorage.removeItem('coonto-rc-pending-'+owner.current+'-'+work.slug);localStorage.removeItem('coonto-rc-local-'+owner.current+'-'+work.slug);}setStatus(dirty.current?'Alterações ainda não salvas.':'Salvo na sua conta.');}catch(error){setStatus(error instanceof Error?error.message:'Não foi possível salvar.');}finally{saving.current=false;}}
 useEffect(()=>{if(!signedIn||!loaded)return;const timer=setTimeout(()=>{void save();},900);return()=>clearTimeout(timer);},[state,signedIn,loaded]);
 useEffect(()=>{const timer=setInterval(()=>{if(dirty.current&&!saving.current&&!blocked.current)void save();},5000);const warn=(e:BeforeUnloadEvent)=>{if(signedIn&&dirty.current){e.preventDefault();e.returnValue='';}};window.addEventListener('beforeunload',warn);return()=>{clearInterval(timer);window.removeEventListener('beforeunload',warn);};},[signedIn,loaded]);
 const unit=work.units[state.unit],key=`${state.unit}:${state.stage}`,selected=state.answers[String(state.unit)],percent=rcProgress(state,work),last=state.unit===work.units.length-1&&state.stage===7;
 const body=[unit.context,unit.reading,unit.question,selected===undefined?'Volte para fazer uma escolha ou continue livremente.':unit.options[selected].consequence,unit.author,unit.evidence,unit.recall,unit.connection][state.stage];
 const sourceHref=work.source.kind==='pdf'?`${work.source.href}#page=${unit.sourceStart}`:work.source.href;
 const entries=rcInteractions(work),journey=state.journey;
 function jumpInteraction(index:number){const item=entries[index];if(!item||!journey)return;audio.current?.pause();setSpeaking(false);setAudioError(false);setHelp(false);canvas.current?.scrollTo({top:0});change({...state,unit:item.unit,stage:0,journey:{...journey,index}});}
 function go(u:number,s:number){if(entries.length){jumpInteraction(entries.findIndex(e=>e.unit===u));return;}audio.current?.pause();setSpeaking(false);canvas.current?.scrollTo({top:0});setHelp(false);setAudioError(false);change({...state,unit:u,stage:s,visited:[...new Set([...state.visited,`${u}:${s}`])]});}
 function exportNotes(){const text=[work.title,...(journey?['Percurso editorial v2 · decisões e notas',...entries.flatMap(({op})=>[op.title,'Hipótese: '+(journey.answers[op.id]===undefined?'—':op.options[journey.answers[op.id]].label),'Nota: '+(journey.notes[op.id]||'—')]),'HISTÓRICO DA EDIÇÃO ANTERIOR (perguntas diferentes)']:[]),`Edição: ${work.version}`,...work.units.flatMap((u,i)=>[u.title,...rcStages.map((stage,j)=>`${stage}: ${state.notes[`${i}:${j}`]||'—'}`),`Hipótese: ${state.answers[String(i)]===undefined?'—':journey?'Alternativa '+(state.answers[String(i)]+1)+' registrada na edição anterior (pergunta diferente).':u.options[state.answers[String(i)]].label}`])].join('\n\n');const url=URL.createObjectURL(new Blob([text],{type:'text/plain;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download=`${work.slug}-anotacoes.txt`;a.click();URL.revokeObjectURL(url);}
 const phase=state.stage===2&&selected!==undefined?'Descobrir':['Decidir','Decidir','Decidir','Descobrir','Entender','Entender','Lembrar','Lembrar'][state.stage];
 const stepTitle=['Entre na história','Entre na situação','Faça sua escolha','Descubra o retorno','O caminho do autor','Confira no texto','O que ficou na memória?','Conecte o que você leu'][state.stage];
 function toggleAudio(id=unit.id){if(speaking){audio.current?.pause();setSpeaking(false);return;}const player=new Audio(`/api/audio/rc/${work.slug}/${id}?edition=${encodeURIComponent(work.version)}`);audio.current?.pause();audio.current=player;setSpeaking(true);player.onended=()=>setSpeaking(false);player.onerror=()=>{setSpeaking(false);setAudioError(true);};void player.play().catch(()=>{setSpeaking(false);setAudioError(true);});}
 async function downloadWork(){
  if(!signedIn){window.location.assign('/checkout/'+work.slug);return;}
  if(dirty.current){await save();if(dirty.current){setStatus('Salve suas alterações antes de baixar.');return;}}
  setPreparing(true);setStatus('Baixando a experiência neste aparelho…');
  try{
   if(!('serviceWorker' in navigator)||!('caches' in window))throw new Error('Este navegador não permite salvar para uso offline.');
   let deviceId=localStorage.getItem('coonto-device-id');if(!deviceId){deviceId=crypto.randomUUID();localStorage.setItem('coonto-device-id',deviceId);}
   const response=await fetch('/api/offline-license',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({deviceId,workSlug:work.slug,label:/Android|iPhone|iPad/i.test(navigator.userAgent)?'Celular ou tablet':'Computador'})});const license=await response.json();if(response.status===403){window.location.assign('/checkout/'+work.slug);return;}if(!response.ok)throw new Error(license.error||'Não foi possível autorizar o aparelho.');
   await navigator.serviceWorker.register('/sw.js');await Promise.race([navigator.serviceWorker.ready,new Promise((_,reject)=>setTimeout(()=>reject(new Error('Recarregue e tente novamente.')),15000))]);
   const cached=await caches.open('coonto-protected-v2');const document=await fetch('/api/works/rc/'+work.slug,{cache:'no-store'});if(!document.ok)throw new Error('Não foi possível baixar a experiência.');
   const owner=document.headers.get('X-Coonto-User');if(!owner)throw new Error('Não foi possível identificar a conta.');
   const offlineShell=await fetch('/offline/rc-reader.html');if(!offlineShell.ok)throw new Error('Não foi possível baixar o leitor.');
   const priorFiles=await cached.keys();for(const file of priorFiles){const prior=await cached.match(file);const user=prior?.headers.get('X-Coonto-User');if(user&&user!==owner){await caches.delete('coonto-protected-v2');break;}}localStorage.removeItem('coonto-rc-local-'+owner+'-'+work.slug);
   const cache=await caches.open('coonto-protected-v2');await cache.put('/offline/rc-reader.html',offlineShell);
   const audioIds=entries.length?entries.flatMap(({op})=>[op.id+'-pre',...op.options.map((_,i)=>op.id+'-r-'+i)]):work.units.map(u=>u.id);let missing=0;for(const id of audioIds){const src=`/api/audio/rc/${work.slug}/${id}`;const media=await fetch(src);if(media.ok)await cache.put(src,media);else{missing++;await cache.delete(src);}}
   await cache.put('/offline/'+work.slug+'.html',new Response(await document.text(),{headers:{'Content-Type':'text/html; charset=utf-8','X-Coonto-User':owner,'X-Coonto-Expires':license.expiresAt}}));
   localStorage.setItem('coonto-offline-user',owner);localStorage.setItem('coonto-rc-offline-'+work.slug,'ready');setStatus('Experiência Coonto baixada. Acesso neste aparelho até '+new Date(license.expiresAt).toLocaleDateString('pt-BR')+'.'+(missing?' '+missing+' áudios indisponíveis; o texto foi baixado.':''));
  }catch(error){setStatus(error instanceof Error?error.message:'Não foi possível baixar.');}finally{setPreparing(false);}
 }
 useEffect(()=>()=>{audio.current?.pause();},[]);
 const rail=(
  <aside className="reader-rail rc-reader-rail"><div className="reader-rail-title"><span>SUA EXPERIÊNCIA</span><strong>{work.title}</strong></div><nav className="reader-rail-actions" aria-label="Ações da leitura">
   <label className="reader-chapter-jump"><span>Ir para {work.source.kind==='pdf'?'capítulo':'movimento'}</span><select id="rc-unit" aria-label={work.source.kind==='pdf'?'Capítulo':'Movimento'} disabled={!loaded} value={state.unit} onChange={e=>go(Number(e.target.value),0)}>{work.units.map((u,i)=><option key={u.id} value={i}>{i+1}. {u.title}</option>)}</select></label>
   <a aria-label="Minha biblioteca" href="/minha-biblioteca"><Library size={18}/><span>Minha biblioteca</span></a>
   <button type="button" aria-label={preparing?'Baixando…':'Baixar neste aparelho'} disabled={preparing||!loaded} onClick={()=>void downloadWork()}><Download size={18}/><span>{preparing?'Baixando…':'Baixar neste aparelho'}</span></button>
   <button type="button" aria-label="Ajuda Coonto" aria-expanded={help} onClick={()=>setHelp(!help)}><CircleHelp size={18}/><span>Ajuda Coonto</span></button>
   <a aria-label="Livro original" href={sourceHref} target="_blank" rel="noopener noreferrer"><BookOpen size={18}/><span>{work.source.kind==='pdf'?'Livro original · PDF externo':'Texto original · Canto I'}</span></a>
   <a aria-label="Baixar livro original completo" href="/catalogo#livros-originais"><Download size={18}/><span>Baixar livro original completo</span></a>
   <button type="button" aria-label="Baixar minhas notas" onClick={exportNotes}><Download size={18}/><span>Baixar minhas notas</span></button>
   {signedIn&&<button type="button" aria-label="Salvar agora" disabled={!loaded} onClick={()=>void save()}><Save size={18}/><span>Salvar agora</span></button>}
  </nav><p className="reader-rail-status" role="status">{status}</p>{!signedIn&&<a className="rc-rail-status" href={'/checkout/'+work.slug}>Adicionar gratuitamente à biblioteca</a>}</aside>
 );
 if(entries.length&&journey){
  const current=entries[journey.index],op=current.op,answer=journey.answers[op.id],answered=answer!==undefined,lastInteraction=journey.index===entries.length-1;
  const choice=(i:number)=>{audio.current?.pause();setSpeaking(false);change({...state,journey:{...journey,answers:{...journey.answers,[op.id]:i}}});};
  const hear=(id:string,label:string)=><button type="button" className="rc-choice" onClick={()=>toggleAudio(id)} aria-label={speaking?'Pausar áudio':label}>{speaking?<Pause size={13}/>:<Play size={13}/>} {speaking?'Pausar áudio':label}</button>;
  return <section className="reader-workspace">{rail}<div className="rc-reader-canvas" ref={canvas}><div className="rc-reader"><div className="rc-phone">
   <header className="rc-hud"><img src="/images/coonto-logo.png" alt="Coonto"/><span>{answered?'Descobrir':'Decidir'}</span><small>{percent}%</small></header><div className="rc-track"><div style={{width:percent+'%'}}/></div>
   <div className="rc-hero"><div className="rc-hero-art" style={{backgroundPosition:'100% 0%'}}/><div><span className="rc-eyebrow">{unit.title}</span><h1>{op.title}</h1></div></div>
   <div className="rc-scene"><fieldset className="rc-card" disabled={!loaded} style={{margin:0,minWidth:0}}>
    <div className="rc-chips"><span className="rc-chip">Capítulo {state.unit+1}/12</span><span className="rc-chip">Interação {journey.index+1}/{entries.length}</span><span className="rc-chip">{op.kind}</span></div>
    {help&&<aside className="rc-help-text"><strong>Como seguir</strong><p>Leia a situação, escolha uma hipótese e compare o retorno com a passagem. Você pode mudar de ideia ou continuar sem responder. Fontes, exercício de memória e anotações ficam disponíveis quando você quiser aprofundar. O progresso conta decisões registradas e não é uma nota.</p><button className="rc-choice" onClick={()=>setHelp(false)}>Fechar ajuda</button></aside>}
    <div className="rc-body">{op.preparation}</div>{hear(op.id+'-pre','Ouvir situação e alternativas')}
    <p className="rc-question">{op.question}</p><div role="group" aria-label={op.question}>{op.options.map((option,i)=><button key={i} type="button" className={'rc-choice '+(answer===i?'selected':'')} aria-pressed={answer===i} onClick={()=>choice(i)}>{option.label}</button>)}</div>
    {answered&&<div className="rc-feedback" aria-live="polite">{op.reveal&&<><small>O QUE ACONTECE NO RELATO</small><p>{op.reveal}</p></>}<small>RETORNO DA SUA HIPÓTESE</small><p>{op.options[answer].consequence}</p><strong>{op.discovery}</strong>{hear(op.id+'-r-'+answer,'Ouvir o retorno')}<details className="rc-reading-text"><summary>Conferir no original · {op.sourceLabel}</summary><p>{op.sourcePages.map(page=><a style={{marginRight:12}} key={page} href={work.source.href+'#page='+page} target="_blank" rel="noopener noreferrer">Página {page} ↗</a>)}</p><p>{work.source.label}</p></details><details className="rc-reading-text"><summary>O que ficou na memória?</summary><p>{op.recall}</p></details><p className="rc-savehint">{op.connection}</p></div>}
    {audioError&&<p className="rc-savehint">A locução não está disponível agora. Continue pelo texto.</p>}
    <details className="rc-notebook" key={op.id}><summary>✎ Caderno Coonto {journey.notes[op.id]?'· com anotação':''}</summary><label htmlFor="rc-reading-note" className="rc-savehint">Sua hipótese, evidência ou dúvida</label><textarea id="rc-reading-note" rows={4} maxLength={2000} value={journey.notes[op.id]||''} onChange={e=>change({...state,journey:{...journey,notes:{...journey.notes,[op.id]:e.target.value}}})}/></details><p className="rc-savehint" role="status">{status}</p>
   </fieldset></div><nav className="rc-reader-nav" aria-label="Navegação da experiência"><button disabled={!loaded||journey.index===0} onClick={()=>jumpInteraction(journey.index-1)}>Voltar</button><button className="primary" disabled={!loaded} onClick={()=>jumpInteraction(lastInteraction?0:journey.index+1)}>{lastInteraction?'Revisitar a obra':!answered?'Continuar sem responder':entries[journey.index+1].unit!==state.unit?'Próximo capítulo':'Continuar'}</button></nav>
   <footer className="rc-reader-footer"><p>{Object.keys(journey.answers).length}/{entries.length} decisões registradas · beta em avaliação</p>{lastInteraction&&<p>Você chegou ao fim deste percurso. <a href="/pesquisa">Avaliar o Coonto</a> · <a href={work.source.href} target="_blank" rel="noopener noreferrer">Ler a obra original</a></p>}<details><summary>Sobre esta edição</summary><p>{work.intro}</p><p>{work.source.label}</p><p>{work.source.license}</p><p>Edição {work.version}.</p>{Object.keys(state.notes).length>0&&<p>Suas notas anteriores permanecem disponíveis em “Baixar minhas notas”.</p>}</details></footer>
  </div></div></div></section>;
 }
 return <section className="reader-workspace">
  {rail}
  <div className="rc-reader-canvas" ref={canvas}><div className="rc-reader"><div className="rc-phone">
   <header className="rc-hud"><img src="/images/coonto-logo.png" alt="Coonto"/><span>{phase}</span><small>{percent}%</small></header><div className="rc-track"><div style={{width:percent+'%'}}/></div>
   <div className="rc-hero"><div className="rc-hero-art" style={{backgroundPosition:work.slug==='memorias-de-martha'?'100% 0%':'100% 100%'}}/><div><span className="rc-eyebrow">{stepTitle}</span><h1>{state.unit===0&&state.stage===0?work.title:unit.title}</h1></div></div>
   <div className="rc-scene"><fieldset className="rc-card" disabled={!loaded} style={{margin:0,minWidth:0}}>
    <div className="rc-phase">AGORA VOCÊ ESTÁ → <strong>{phase}</strong></div>
    <div className="rc-scene-meta"><div className="rc-chips"><span className="rc-chip">{work.source.kind==='pdf'?'Capítulo':'Movimento'} {state.unit+1}/{work.units.length}</span><span className="rc-chip">{work.author}</span></div>{state.stage===0&&<button className="rc-icon" type="button" aria-label={speaking?'Pausar abertura':'Ouvir abertura'} onClick={()=>toggleAudio()}>{speaking?<Pause size={13}/>:<Play size={13}/>}</button>}</div>
    {help&&<aside className="rc-help-text" aria-label="Ajuda nesta etapa"><strong>O que fazer agora</strong><p>{['Conheça a situação antes de interpretar.','Leia e observe o que mudou. O texto do Coonto é uma síntese; o original está disponível ao lado.','Escolha uma hipótese e compare o retorno. Você pode mudar de ideia.','Observe o retorno da sua hipótese. Ele aponta o que investigar no texto.','Descubra o caminho construído pelo autor.','Confira as passagens que sustentam ou complicam sua leitura.','Tente lembrar antes de reler.','Conecte este momento ao restante da obra.'][state.stage]}</p><p>Use Continuar para seguir e Voltar para revisitar. O Caderno Coonto guarda suas notas.</p><button type="button" className="rc-choice" onClick={()=>setHelp(false)}>Fechar ajuda</button></aside>}
    <div className="rc-body">{state.stage===2?unit.reading:body}</div>
    {audioError&&<p className="rc-savehint">A locução não está disponível agora. Continue pelo texto.</p>}
    {state.stage===2&&<><p className="rc-question">{unit.question}</p><div role="group" aria-label={unit.question}>{unit.options.map((option,i)=><button key={i} type="button" className={'rc-choice '+(selected===i?'selected':'')} aria-pressed={selected===i} onClick={()=>change({...state,answers:{...state.answers,[String(state.unit)]:i},visited:[...new Set([...state.visited,`${state.unit}:3`])]})}>{option.label}</button>)}</div>{selected!==undefined&&<div className="rc-feedback" aria-live="polite"><small>LEITURA E EVIDÊNCIA</small><p>{unit.options[selected].consequence}</p></div>}</>}
    {state.stage===1&&work.source.kind==='verses'&&<details open className="rc-reading-text"><summary>Texto integral · versos {unit.sourceStart}–{unit.sourceEnd}</summary><ol start={unit.sourceStart}>{verses.slice(unit.sourceStart-1,unit.sourceEnd).map((verse,i)=><li key={i}>{verse}</li>)}</ol></details>}
    {(state.stage===1||state.stage===4||state.stage===5)&&<p className="rc-source-link"><a aria-label="Livro original" href={sourceHref} target="_blank" rel="noopener noreferrer">{work.source.kind==='pdf'?'Ver o caminho no texto de Júlia':'Conferir a edição e a tradução'} ↗</a></p>}
    <details className="rc-notebook" key={key}><summary>✎ Caderno Coonto {state.notes[key]?'· com anotação':''}</summary><label htmlFor="rc-reading-note" className="rc-savehint">Sua hipótese, evidência ou dúvida</label><textarea id="rc-reading-note" rows={4} maxLength={2000} value={state.notes[key]||''} onChange={e=>change({...state,notes:{...state.notes,[key]:e.target.value}})} placeholder="Que passagem sustenta sua ideia?"/></details><p className="rc-savehint" role="status">{status}</p>
   </fieldset></div>
   <nav className="rc-reader-nav" aria-label="Navegação da experiência"><button type="button" disabled={!loaded||(state.unit===0&&state.stage===0)} onClick={()=>go(state.stage===0?state.unit-1:state.unit,state.stage===0?7:state.stage===4?2:state.stage-1)}>Voltar</button><button type="button" className="primary" disabled={!loaded} onClick={()=>last?go(0,0):go(state.stage===7?state.unit+1:state.unit,state.stage===7?0:state.stage===2?4:state.stage+1)}>{last?'Revisitar a obra':state.stage===7?(work.source.kind==='pdf'?'Próximo capítulo':'Próximo movimento'):state.stage===0?'Entrar na situação':'Continuar'}</button></nav>
   <footer className="rc-reader-footer"><p>{state.unit+1}/{work.units.length} · {phase} · beta em revisão</p>{last&&<p>Você chegou ao fim deste percurso. <a href="/catalogo">Escolher outra obra</a> · <a href="/pesquisa">Avaliar o Coonto</a></p>}<details><summary>Sobre a edição e as fontes</summary><p>{work.intro}</p><p>{work.source.kind==='pdf'?'O download da experiência contém as sínteses do Coonto. O PDF do livro original é um arquivo separado.':'O download contém a experiência e os 136 versos do Canto I. Não contém a Divina Comédia completa.'}</p><p>{work.source.label}</p><p>{work.source.license}</p><p>Edição {work.version}. O progresso indica etapas visitadas.</p></details></footer>
  </div></div></div>
 </section>;
}
