import type {RcWork,RcState} from '@/lib/rc-schema';
export function rcOfflineHtml(data:{work:RcWork;state:RcState;revision:number;userId:string;verses:string[]},css:string){
 const encoded=JSON.stringify(data).replace(/</g,'\\u003c').replace(/>/g,'\\u003e');
 return `<!doctype html><html lang="pt-BR"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Coonto · leitura offline</title><style>body{margin:0;background:#031815}${css}</style><div class="rc-reader"><div class="rc-phone" id="app"></div></div><script>
const data=${encoded},work=data.work,pendingKey='coonto-rc-pending-'+data.userId+'-'+work.slug,key='coonto-rc-local-'+data.userId+'-'+work.slug;
let state=data.state;try{const old=JSON.parse(localStorage.getItem(key)||'null');if(old&&old.contentVersion===work.version&&old.revision===data.revision&&old.state.unit<work.units.length&&old.state.stage>=0&&old.state.stage<8)state=old.state;}catch{}
const phases=['Decidir','Decidir','Decidir','Descobrir','Entender','Entender','Lembrar','Lembrar'],titles=['Entre na história','Entre na situação','Faça sua escolha','Descubra o retorno','O caminho do autor','Confira no texto','O que ficou na memória?','Conecte o que você leu'];let player=null;
const esc=x=>String(x).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function save(){const value={state,revision:data.revision,contentVersion:work.version};try{localStorage.setItem(key,JSON.stringify(value));localStorage.setItem(pendingKey,JSON.stringify(value));document.getElementById('hint').textContent='Guardado neste aparelho. Reabra a obra com internet para sincronizar.';}catch{document.getElementById('hint').textContent='Sem espaço no aparelho. Mantenha esta página aberta e copie suas notas.';}}
function render(){const u=work.units[state.unit],selected=state.answers[String(state.unit)],k=state.unit+':'+state.stage,phase=state.stage===2&&selected!==undefined?'Descobrir':phases[state.stage],bodies=[u.context,u.reading,u.reading,selected===undefined?'Volte para escolher uma hipótese ou continue livremente.':u.options[selected].consequence,u.author,u.evidence,u.recall,u.connection],percent=Math.round(new Set(state.visited).size/(work.units.length*8)*100),last=state.unit===work.units.length-1&&state.stage===7;
 document.title='Coonto · '+work.title;
 document.getElementById('app').innerHTML='<header class="rc-hud"><img src="/images/coonto-logo.png" alt="Coonto"><span>'+phase+'</span><small>'+percent+'%</small></header><div class="rc-track"><div style="width:'+percent+'%"></div></div><div class="rc-hero"><div><span class="rc-eyebrow">'+titles[state.stage]+'</span><h1>'+esc(state.unit===0&&state.stage===0?work.title:u.title)+'</h1></div></div><div class="rc-scene"><div class="rc-card"><div class="rc-phase">AGORA VOCÊ ESTÁ → <strong>'+phase+'</strong></div><div class="rc-scene-meta"><span class="rc-chip">'+(work.source.kind==='pdf'?'Capítulo':'Movimento')+' '+(state.unit+1)+'/'+work.units.length+'</span>'+(state.stage===0?'<button type="button" class="rc-icon" onclick="playAudio()" aria-label="Ouvir abertura">▶</button>':'')+'</div><div class="rc-body">'+esc(bodies[state.stage])+'</div>'+(state.stage===2?'<p class="rc-question">'+esc(u.question)+'</p>'+u.options.map((o,i)=>'<button type="button" class="rc-choice '+(selected===i?'selected':'')+'" onclick="choose('+i+')">'+esc(o.label)+'</button>').join('')+(selected===undefined?'':'<div class="rc-feedback"><small>LEITURA E EVIDÊNCIA</small>'+esc(u.options[selected].consequence)+'</div>'):'')+(state.stage===1&&work.source.kind==='verses'?'<details open class="rc-reading-text"><summary>Versos '+u.sourceStart+'–'+u.sourceEnd+'</summary><ol start="'+u.sourceStart+'">'+data.verses.slice(u.sourceStart-1,u.sourceEnd).map(v=>'<li>'+esc(v)+'</li>').join('')+'</ol></details>':'')+'<details class="rc-notebook"><summary>✎ Caderno Coonto</summary><textarea aria-label="Minha anotação" maxlength="2000" oninput="note(this.value)">'+esc(state.notes[k]||'')+'</textarea></details><p class="rc-savehint" id="hint">Cópia neste aparelho. Suas notas serão sincronizadas quando você voltar à leitura com internet.</p></div></div><nav class="rc-reader-nav"><button type="button" onclick="go(-1)" '+(state.unit===0&&state.stage===0?'disabled':'')+'>Voltar</button><button type="button" class="primary" onclick="go(1)">'+(last?'Revisitar a obra':state.stage===0?'Entrar na situação':state.stage===7?'Próximo '+(work.source.kind==='pdf'?'capítulo':'movimento'):'Continuar')+'</button></nav><footer class="rc-reader-footer"><label>Ir para '+(work.source.kind==='pdf'?'capítulo':'movimento')+' <select onchange="jump(Number(this.value))">'+work.units.map((v,i)=>'<option value="'+i+'" '+(i===state.unit?'selected':'')+'>'+(i+1)+'. '+esc(v.title)+'</option>').join('')+'</select></label><p><button type="button" class="rc-choice" onclick="help()">Ajuda Coonto</button></p><p>'+esc(work.source.label)+'<br>'+esc(work.source.license)+'</p><p>Beta em revisão · '+esc(work.version)+'</p></footer>';
}
function stop(){if(player)player.pause();player=null;}
window.go=n=>{stop();let index=state.unit*8+state.stage+n;if(n===1&&state.stage===2)index++;if(n===-1&&state.stage===4)index--;if(index>=work.units.length*8)index=0;if(index<0)return;state.unit=Math.floor(index/8);state.stage=index%8;state.visited=[...new Set([...state.visited,state.unit+':'+state.stage])];render();save();window.scrollTo(0,0);};
window.jump=i=>{stop();state.unit=i;state.stage=0;state.visited=[...new Set([...state.visited,i+':0'])];render();save();window.scrollTo(0,0);};
window.choose=i=>{state.answers[String(state.unit)]=i;state.visited=[...new Set([...state.visited,state.unit+':3'])];render();save();};window.note=v=>{state.notes[state.unit+':'+state.stage]=v;save();};
window.help=()=>alert('Leia a situação, faça sua escolha e confira o retorno. Continue para encontrar o caminho do autor, sustentar sua interpretação e lembrar. Você pode voltar, escolher outro capítulo e registrar suas ideias no Caderno Coonto.');
window.playAudio=()=>{if(player){stop();return;}player=new Audio('/api/audio/rc/'+work.slug+'/'+work.units[state.unit].id);player.onerror=()=>{stop();document.getElementById('hint').textContent='Este áudio não foi baixado. Continue pelo texto.';};player.onended=stop;player.play().catch(()=>{stop();});};
window.addEventListener('online',()=>{document.getElementById('hint').innerHTML='A conexão voltou. <a href="/rc/'+work.slug+'">Abra a leitura para sincronizar suas notas</a>.';});render();
</script></html>`;
}
