import {z} from 'zod';
export const rcSlugs=['memorias-de-martha','divina-comedia-canto-i'] as const;
export const rcSlugSchema=z.enum(rcSlugs);
const text=z.string().trim().min(1).max(6000);
const interactionId=z.string().regex(/^cap-(?:[1-9]|1[0-2])-i-[1-3]$/);
const interaction=z.object({id:interactionId,title:text,kind:text,preparation:text,question:text,options:z.array(z.object({label:text,consequence:text})).length(3),reveal:z.string().max(6000),discovery:text,recall:text,connection:text,sourceLabel:text,sourcePages:z.array(z.number().int().min(9).max(166)).min(1).max(12)});
export const rcWorkSchema=z.object({slug:rcSlugSchema,title:text,author:text,version:z.string().max(80),intro:text,source:z.object({label:text,href:z.string().url().refine(s=>s.startsWith('https://')),license:text,kind:z.enum(['pdf','verses'])}),units:z.array(z.object({id:z.string().regex(/^(cap|mov)-\d{1,2}$/),title:text,context:text,reading:text,question:text,options:z.array(z.object({label:text,consequence:text})).length(3),author:text,evidence:text,recall:text,connection:text,sourceStart:z.number().int().positive(),sourceEnd:z.number().int().positive(),interactions:z.array(interaction).min(1).max(3).optional()})).min(1).max(12)}).superRefine((work,ctx)=>{const ids=new Set<string>();for(const u of work.units)for(const [i,o] of (u.interactions||[]).entries()){if(work.slug!=='memorias-de-martha'||o.id!==u.id+'-i-'+(i+1)||ids.has(o.id))ctx.addIssue({code:z.ZodIssueCode.custom,message:'Interação fora do capítulo ou duplicada'});ids.add(o.id);}if(work.units.some(u=>u.interactions)&&work.units.some(u=>!u.interactions))ctx.addIssue({code:z.ZodIssueCode.custom,message:'Todos os capítulos precisam de interações'});});
export type RcWork=z.infer<typeof rcWorkSchema>;
export const rcStages=['Contexto','Leitura','Decisão','Consequência','Autor','Interpretação','Recuperação','Conexão'];
const stepKey=z.string().regex(/^(?:0|[1-9]|1[01]):[0-7]$/);
export const rcStateSchema=z.object({unit:z.number().int().min(0).max(11),stage:z.number().int().min(0).max(7),visited:z.array(stepKey).max(96),answers:z.record(z.string().regex(/^(?:0|[1-9]|1[01])$/),z.number().int().min(0).max(2)),notes:z.record(stepKey,z.string().max(2000)),journey:z.object({index:z.number().int().min(0).max(35),answers:z.record(interactionId,z.number().int().min(0).max(2)),notes:z.record(interactionId,z.string().max(2000))}).strict().optional()}).strict();
export type RcState=z.infer<typeof rcStateSchema>;
export const initialRcState:RcState={unit:0,stage:0,visited:['0:0'],answers:{},notes:{}};
export function validRcState(state:RcState,count:number|RcWork){const work=typeof count==='number'?null:count;const total=typeof count==='number'?count:count.units.length;if(state.journey){if(!work)return false;const entries=rcInteractions(work);const ids=new Set(entries.map(e=>e.op.id));if(!entries[state.journey.index]||entries[state.journey.index].unit!==state.unit||!Object.keys(state.journey.answers).every(id=>ids.has(id))||!Object.keys(state.journey.notes).every(id=>ids.has(id)))return false;}return state.unit<total&&state.visited.every(k=>Number(k.split(':')[0])<total)&&Object.keys(state.notes).every(k=>Number(k.split(':')[0])<total)&&Object.keys(state.answers).every(k=>Number(k)<total);}
export function rcProgress(state:RcState,count:number|RcWork){if(typeof count!=='number'&&rcInteractions(count).length)return Math.round(Object.keys(state.journey?.answers||{}).length/rcInteractions(count).length*100);return Math.round(new Set(state.visited).size/((typeof count==='number'?count:count.units.length)*8)*100);}

export function rcInteractions(work:RcWork){return work.units.flatMap((u,unit)=>(u.interactions||[]).map(op=>({unit,op})));}
// Old chapter answers and notes stay in their original fields; they never answer new questions.
export function prepareRcState(state:RcState,work:RcWork):RcState{const entries=rcInteractions(work);if(!entries.length)return state;if(state.journey&&validRcState(state,work))return state;return {...state,stage:0,journey:{index:Math.max(0,entries.findIndex(e=>e.unit===state.unit)),answers:{},notes:{}}};}
